### ISSUE TITLE
大模型V2版本怎么使用？

### ISSUE THREAD

**Issue by zth1987** [theajack/spark-node#2]
大模型V2版本怎么使用？

**Comment by theajack** [comment]
暂时不支持 V2 版本 的API，还没开发

**Comment by theajack** [comment]
> 大模型V2版本怎么使用？

@zth1987 已经支持了 version字段可以使用 V2，V3版本的API

**Comment by zth1987** [comment]
> > 大模型V2版本怎么使用？
> 
> @zth1987 已经支持了 version字段可以使用 V2，V3版本的API

谢谢！
